# Change these first
owner: joshfester # Your GitHub organization or username, where this repository lives
repo: grammy-upptime # The name of this repository

sites:
  - name: GrammyGo
    url: https://go.grammy.com/wp-login.php

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: ocean
  css: "a.logo div { display: none; }"
  baseUrl: /grammy-upptime
  logoUrl: https://go.grammy.com/wp-content/uploads/2023/09/GRAMGO_lockup_horizontal_white.png
  name: GrammyGo Uptime Monitor
  introMessage: This uses **real-time** data from our [GitHub repository](https://github.com/joshfester/grammy-upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/joshfester/grammy-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
